### ISSUE TITLE
steps to merge custom API to frontend

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/helper-custom-api#13]
@Perevedko: need a listing of steps taken to integrate custom_api.md to frontend app

**Comment by Perevedko** [comment]
1. copy `helpers/custom_api/custom_api.py -> frontend-app/apps/helpers/custom_api.py` and `helpers/custom_api/test_custom_api.py -> frontend-app/apps/tests/test_custom_api.py`
2. changed import of custom_api in test_custom_api.py: `import apps.helpers.custom_api as custom_api`
3. `frontend-app/apps/views/time_series.py`: added import of `custom_api`; registered error handler for `custom_api.InvalidUsage`, changed `time_series_api_interface` function to use `custom_api.CustomGET`
4. `$ pytest`

**Comment by epogrebnyak** [comment]
Some unprioritised notes:
- what about custom error class?
- maybe can install custom_api.md via requirements.txt 
- separate repo helper-custom-api?

**Comment by Perevedko** [comment]
> what about custom error class?
we can remove it and use `custom_api.InvalidException`
> maybe can install custom_api.md via requirements.txt
> separate repo helper-custom-api?
i think we can separate repo, make scripts in it for building whl package `custom_api`, then use `whl` in `frontend-app` and `db`
